### PR TITLE
sshd: Allow connection on ethernet, ppp, wifi client & ap.

### PR DESCRIPTION
**Pull request by andrewleech**
Rework firewall to allow 22 on dbg_if, wlan_if, ext_if & ppp_if in all pf rules.

### CODE REVIEW

**Comment by olli991** [comment]
Does this need additional testing? Can't we just merge it?

**Comment by andrewleech** [comment]
Yeah probably fine to merge. I tested my wifi access still worked with it, but haven't been able to test the Ethernet.

**Comment by olli991** [comment]
Ah so we should maybe wait on one success test then

**Comment by jilleb** [comment]
I can test ethernet today in the car :-)

**Comment by Honki26** [comment]
ethernet is working here since few days, good work!

**Comment by Honki26** [comment]
here the uninstall script:

mount -uw /net/mmx/mnt/app
mount -uw /net/mmx/mnt/system
rm -rf /net/mmx/mnt/app/eso/hmi/engdefs/scripts/ssh
rm -rf /net/mmx/mnt/app/root/scp*
rm -rf /net/mmx/mnt/app/root/.profile
rm -rf /net/mmx/mnt/app/root/.ssh
mv -f /net/mmx/mnt/system/etc/inetd.conf.bu /net/mmx/mnt/system/etc/inetd.conf
for PF in /net/mmx/mnt/system/etc/pf*.conf ; do
if [ -f ${PF}.bu ]; then
mv -f ${PF}.bu ${PF}
fi
done
mount -ur /net/mmx/mnt/app
mount -ur /net/mmx/mnt/system

**Comment by Honki26** [comment]
and to make all writeable after scp login:

RW=`grep -i mount /net/mmx/mnt/app/root/.profile`
if [ $? != 0 ]; then
mount -uw /net/mmx/mnt/app
echo "/bin/mount -uw /net/mmx/fs/sda0 2>/dev/null" >> /net/mmx/mnt/app/root/.profile
echo "/bin/mount -uw /net/mmx/fs/sda1 2>/dev/null" >> /net/mmx/mnt/app/root/.profile
echo "/bin/mount -uw /mnt/app" >> /net/mmx/mnt/app/root/.profile
echo "/bin/mount -uw /mnt/system" >> /net/mmx/mnt/app/root/.profile
echo "root is now writable in ssh ;-)"
else
echo "writable root in ssh is already there..."
fi

**Comment by andrewleech** [comment]
>  for PF in /net/mmx/mnt/system/etc/pf*.conf ; do
> if [ -f ${PF}.bu ]; then
> mv -f ${PF}.bu ${PF}
> fi
> done

Thanks, yeah I'd forgotten to update the uninstall script with the extra pf changes

**Comment by andrewleech** [comment]
> 
> 
> and some script lines to make all writeable after scp login:
> 
> mount -uw /net/mmx/mnt/app
> echo "/bin/mount -uw /net/mmx/fs/sda0 2>/dev/null" >> /net/mmx/mnt/app/root/.profile
> echo "/bin/mount -uw /net/mmx/fs/sda1 2>/dev/null" >> /net/mmx/mnt/app/root/.profile
> echo "/bin/mount -uw /mnt/app" >> /net/mmx/mnt/app/root/.profile
> echo "/bin/mount -uw /mnt/system" >> /net/mmx/mnt/app/root/.profile
> mount -ur /net/mmx/mnt/app

Unfortunately I don't think `.profile` is run automatically when doing a scp, so you still need to login to ssh first (to run these) then you can scp.

I'm not sure about making these all `rw` by default when logging into ssh, what do you think @jilleb & @olli991 ? Would this snippet be better off in the wiki as something people can run manually if they want it?

**Comment by Honki26** [comment]
> Unfortunately I don't think `.profile` is run automatically when doing a scp, so you still need to login to ssh first (to run these) then you can scp.

In WinSCP .profile mod is working on every Login

**Comment by andrewleech** [comment]
> 
> In WinSCP .profile mod is working on every Login

Ah, yes WinSCP uses a normal ssh login behind the scenes to get the directory listings, so that would work

**Review by Fadada86 — APPROVED** [review]

**Pull request merged**
