### PR TITLE
Script for virtual cockpit VNC client installation

### PR DESCRIPTION
**Pull request by OneB1t**

### CODE REVIEW

**Comment by olli991** [comment]
In case someone what to revert his unit can you maybe also add an restore / uninstall script here?

**Comment by OneB1t** [comment]
remove "/navigation/opengl-render-qnx" (this is enough to disable this functionality)
and remove section "# QNX VNC CLIENT" from /etc/boot/startup.sh

not sure if i want to mess with startup.sh as that can lead to brick

**Comment by Biorn1950** [comment]
> 

Hello what is vnc client for virtual cockpit exactly?

**Comment by Biorn1950** [comment]
Hello @OneB1t what is vnc client for virtual cockpit exactly?

**Comment by OneB1t** [comment]
> Hello @OneB1t what is vnc client for virtual cockpit exactly?

https://github.com/OneB1t/VcMOSTRenderMqb

**Comment by olli991** [comment]
WIll merge base PR and will adjust if afterwards with more options

**Comment by Ads74100** [comment]
Hello and for Virgin cokpit gen 1 Where can find scrypt please

**Pull request merged**
