### PR TITLE
Update offset to correct size

### PR DESCRIPTION
**Pull request by andy0172**

### CODE REVIEW

**Comment by jilleb** [comment]
Hmm, I never used this when flashing ifs-root... are you sure it works?

**Comment by andy0172** [comment]
Yes tested it. Working 100%

**Comment by ArHeGo** [comment]
Hello, this ToolBox can be installed in a US specs Device?

**Comment by yeeefang** [comment]
Actually there comes with 2 kinds of ifs-root file depending on the origination of the file.
The complete ifs-root consisting of stage 1 & 2 is about 19-22 Mb and starting at hex 0x540000;
The partial ifs-root  which is  only consisting of stage 2 is about 15 Mb and starting at hex 0xBA0000.

This image is quoted from an instruction on how-to patching ifs-root file and may solve this issue.

MIB2

**Pull request closed without merging**
